Generic_module(SortedTable)

template (sortedtable)

#Sorted_table (AtomAtom, Atom, Atom)
#Sorted_table (AtomInt,  Atom, Integer)
#Sorted_table (AtomRef,  Atom, Refany)
#Sorted_table (AtomText, Atom, Text)

#Sorted_table (IntAtom, Integer, Atom)
#Sorted_table (IntInt,  Integer, Integer)
#Sorted_table (IntRef,  Integer, Refany)
#Sorted_table (IntText, Integer, Text)

#Sorted_table (RefAtom, Refany, Atom)
#Sorted_table (RefInt,  Refany, Integer)
#Sorted_table (RefRef,  Refany, Refany)
#Sorted_table (RefText, Refany, Text)

#Sorted_table (TextAtom, Text, Atom)
#Sorted_table (TextInt,  Text, Integer)
#Sorted_table (TextRef,  Text, Refany)
#Sorted_table (TextText, Text, Text)
