Generic_interface("Sequence")
Generic_interface("SequenceRep")
Generic_implementation("Sequence")

template (sequence)

#Sequence (Atom, Atom)
#Sequence (Int,  Integer)
#Sequence (Ref,  Refany)
#Sequence (Text, Text)
